language: rust
rust:
  - stable

before_script: |
  rustup component add rustfmt-preview &&
  rustup component add clippy-preview
script: |
  cargo fmt -- --check &&
  cargo clippy -- -D all &&
  cargo build --verbose &&
  cargo build --no-default-features --verbose &&
  cargo test  --verbose &&
  cargo test --no-default-features --verbose
cache: cargo
